name: Build & Test

on: [push, pull_request, workflow_dispatch]

jobs:
  connectors:
    name: connector-*
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Prepare cache key
        id: cache-key
        shell: bash
        run: echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          # The cache key is changed every month to prevent unlimited growth.
          key: maven-cache-${{ steps.cache-key.outputs.date }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Build with Maven
        run: ./mvnw clean verify -am -ntp -P !default,connector-apps
      - name: Pushes coverage
        run: bash <(curl -s https://codecov.io/bash)
  not-connectors:
    name: aggregator, backend, engine, recipients-resolver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Prepare cache key
        id: cache-key
        shell: bash
        run: echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          # The cache key is changed every month to prevent unlimited growth.
          key: maven-cache-${{ steps.cache-key.outputs.date }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Build with Maven
        run: ./mvnw clean verify -am -ntp -P !default,not-connector-apps
      - name: Pushes coverage
        run: bash <(curl -s https://codecov.io/bash)
      - uses: actions/upload-artifact@v3
        name: Upload openapi.json
        with:
          name: openapi
          path: |
            backend/target/api/notifications/v1/openapi.json
            backend/target/api/notifications/v2/openapi.json
            backend/target/api/integrations/v1/openapi.json
            backend/target/api/integrations/v2/openapi.json
            backend/target/api/private/v1/openapi.json
            backend/target/api/private/v2/openapi.json
            backend/target/internal/openapi.json
  admin-console:
    name: admin-console
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Verify if admin-console changed
        id: admin-console-changed
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: admin-console
      - name: Prepare cache key
        if: steps.admin-console-changed.outputs.any_changed == 'true'
        id: cache-key
        shell: bash
        run: echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
      - name: Cache Maven dependencies
        if: steps.admin-console-changed.outputs.any_changed == 'true'
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          # The cache key is changed every month to prevent unlimited growth.
          key: maven-cache-${{ steps.cache-key.outputs.date }}
      - name: Cache Yarn dependencies
        if: steps.admin-console-changed.outputs.any_changed == 'true'
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          # The cache key is changed every month to prevent unlimited growth.
          key: yarn-cache-${{ steps.cache-key.outputs.date }}
      - name: Build admin-console
        if: steps.admin-console-changed.outputs.any_changed == 'true'
        run: ./mvnw clean verify -am -ntp -P !default,admin-console
      - name: Push admin-console
        if: steps.admin-console-changed.outputs.any_changed == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: bash .github/scripts/push-admin-console.sh
